SkillModifier.register_modifier("void_power", 250, nil, function(skill, data)
    gm.get_script_ref(102397)(skill, skill.parent)
    SkillModifier.change_attr_func(skill, "damage", data, function(origin_value)
        return origin_value * 2 ^ Utils.empty_skill_num
    end)
    SkillPickup.add_local_drop_callback(skill, function()
        gm.get_script_ref(102397)(skill, skill.parent)
    end)
    SkillPickup.add_local_pick_callback(skill, function()
        gm.get_script_ref(102397)(skill, skill.parent)
    end)
end, function(skill, data)
    SkillPickup.remove_local_drop_callback(skill)
    SkillPickup.remove_local_pick_callback(skill)
    SkillModifier.restore_attr(skill, "damage", data)
end)
